# Generated by Django 3.1.5 on 2021-01-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='BRDDesc',
            field=models.TextField(blank=True, null=True, verbose_name='Brand Description'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='BRDName',
            field=models.CharField(max_length=100, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='VARDesc',
            field=models.TextField(blank=True, null=True, verbose_name='Variant Description'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='VARName',
            field=models.CharField(max_length=100, verbose_name='Variant Name'),
        ),
    ]
