# Generated by Django 3.1.5 on 2021-01-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210108_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDInstock',
            field=models.BooleanField(default=True, verbose_name='Product Stock'),
        ),
    ]
