# Generated by Django 3.1.5 on 2021-01-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_prdinstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDDiscount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='Product Discount'),
        ),
    ]
