# Generated by Django 3.1.5 on 2021-01-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_prddiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDIImage',
            field=models.ImageField(default='null', upload_to='product/', verbose_name='Image'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
